export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST'
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS'
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL'
export const BRAND_DETAILS_RESET = 'BRAND_DETAILS_RESET'
